from django.urls import path
from django.contrib.auth import views as auth_views
from flyer_builder_manager import views

app_name = 'flyer_builder_manager'
urlpatterns = [

    path('', auth_views.LoginView.as_view(redirect_authenticated_user=True), name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('projects', views.project_list, name='projects'),
    path("get_themes", views.get_themes, name='get_themes'),
    path('create-empty-project', views.create_empty_project, name='create_empty_project'),
    path('create-excel-project', views.create_excel_project, name='create_excel_project'),
    path('project/<int:uid>/delete', views.delete_project, name='delete_project'),
    path('project/<int:project_id>/preview', views.preview_project, name='preview_project'),
    path('projects/<int:project_id>/test-pdf', views.test_pdf, name='test_pdf'),
    path('projects/<int:project_id>/generate-pdf', views.generate_pdf, name='generate_pdf'),
    path('projects/<int:project_id>/<str:pdf_type>/pdf-generating-status', views.pdf_generating_status, name='pdf_generating_status'),
    path('projects/<int:project_id>/initialization-status', views.initialization_status, name='initialization_status'),
    path('projects/<int:project_id>/products/<int:product_id>/delete', views.delete_project_product, name='delete_project_product'),
    path('projects/<int:project_id>/pages/<int:page_number>/delete', views.delete_project_page, name='delete_project_page'),
    path('projects/<int:project_id>/pages/<int:page_number>/clear', views.clear_project_page, name='clear_project_page'),
    path('projects/<int:project_id>/pages/<int:page_number>/switch', views.switch_project_page, name='switch_project_page'),
    path('projects/<int:project_id>/pages/<int:page_number>/change-name', views.change_page_name, name='change_page_name'),
    path('project/<int:project_id>/page/<int:page_number>', views.edit_project_page, name='edit_project_page'),
    path('projects/<int:project_id>/pages/new', views.new_project_page, name='new_project_page'),
    path('projects/<int:project_id>/update-products-data-by-excel', views.update_products_data_by_excel, name='update_products_data_by_excel'),
    path('products/search', views.search_product, name='search_product'),
    path('products/add', views.add_product, name='add_product'),
    path('catalog/products', views.catalog_products, name='catalog_products'),
    path('catalog/products/<int:product_id>/edit', views.edit_product, name='edit_product'),
    path('catalog/products/<int:product_id>/show', views.show_product, name='show_product'),
    path('catalog/products/<int:product_id>/delete', views.delete_catalog_product, name='delete_catalog_product'),
    path('catalog/products/<int:product_id>/images/<int:image_id>/delete', views.delete_catalog_product_image, name='delete_catalog_product_image'),
    path('products/subcategory-select-options', views.subcategory_select_options, name='subcategory_select_options'),
    path('project/<int:project_id>/page/<int:page_number>/partial', views.project_page_partial, name='project_page_partial'),
    path('projects/<int:project_id>/pages/<int:page_number>/zoom', views.zoom, name='zoom'),
    path('projects/<int:project_id>/pages/<int:page_number>/change-template/<int:template_id>', views.project_page_change_template, name='project_page_change_template'),
    path('project/<int:project_id>/available-products/partial', views.project_available_products_partial, name='project_available_products_partial'),
    path('project/import-catalog-product-to-cell', views.import_catalog_product_to_cell, name='import_catalog_product_to_cell'),
    path('project/swap-cells', views.swap_cells, name='swap_cells'),
    path('projects/<int:project_id>/pages/<int:page_number>/cells/<int:cell_id>/merge-split/<str:operation>', views.merge_split_cells, name='merge_split_cells'),
    path('projects/<int:project_id>/products/<int:product_id>', views.get_project_product_data, name='get_project_product_data'),
    path('project/edit-product-data', views.edit_project_product_data, name='edit_project_product_data'),
    path('projects/<int:project_id>/products/<int:product_id>/edit', views.edit_project_product_data, name='edit_project_product_data'),
    path('projects/<int:project_id>/send-to-agency', views.send_to_agency, name='send_to_agency'),
    path('campaign/<int:seller_code>', views.campaign, name='campaign'),
    path('download-file/<int:project_id>/<int:seller>', views.download, name='download'),
    path('search-header-banner', views.search_header_banner, name='search_header_banner'),
    path('project/import-image-to-cell', views.import_image_to_cell, name='import_image_to_cell'),
    path('projects/<int:project_id>/products/<int:product_id>/style', views.get_project_product_style_data, name='get_project_product_style_data'),
    path('projects/<int:project_id>/products/<int:product_id>/edit_style', views.edit_project_product_style_data, name='edit_project_product_style_data'),
    path('projects/<int:project_id>/page/<int:page_id>/edit_cell_style', views.edit_project_cell_style_data, name='edit_project_cell_style_data'),
    path('projects/<int:project_id>/page/<int:page_id>/edit_page_style', views.edit_project_page_style_data,
         name='edit_project_page_style_data'),
    path('projects/<int:project_id>/page/<int:page_id>/upload_image', views.update_page_image,
         name='update_page_image'),
    path('project/<int:project_id>/product_list', views.project_product_list, name='project_product_list'),
    path('projects/<int:project_id>/save_page', views.save_page,
         name='save_page'),
    path('project/<int:project_id>/<int:product_id>/update_product', views.update_product, name='update_product'),
    path('project/<int:project_id>/<int:product_id>/delete_product', views.delete_product, name='delete_product'),
    path('project/<int:project_id>/page_pdf/partial', views.project_page_pdf_partial, name='project_page_pdf_partial'),
    path('project/<int:project_id>/stopper', views.project_stopper, name='project_stopper'),
    path('project/<int:project_id>/poster', views.project_poster, name='project_poster'),
    path('projects/<int:project_id>/<str:element>/edit_style', views.edit_project_style_data,
         name='edit_project_style_data'),
    path('project/<int:project_id>/<str:element>/partial', views.project_partial, name='project_partial'),
    path('projects/<int:project_id>/<str:element>/upload_image', views.update_element_image,
         name='update_element_image'),
    path('projects/<int:project_id>/save_stopper', views.save_stopper,
         name='save_stopper'),
    path('projects/<int:project_id>/save_poster', views.save_poster,
         name='save_poster'),
    path('projects/<int:project_id>/<str:element>/edit_data_position', views.edit_data_position,name='edit_data_position')
]